import '../models/climb_attempt.dart';

final List<ClimbAttempt> mockClimbs = [
  ClimbAttempt(
    grade: "V3",
    styleTags: ["Overhang", "Crimpy"],
    attempts: 2,
    result: "topped",
    thoughts: "Felt strong after warmup",
    date: DateTime.now().subtract(Duration(days: 1)),
  ),
  ClimbAttempt(
    grade: "V4",
    styleTags: ["Slab"],
    attempts: 3,
    result: "fell",
    thoughts: "Slipped at the top",
    date: DateTime.now().subtract(Duration(days: 1)),
  ),
  ClimbAttempt(
    grade: "V2",
    styleTags: ["Volume", "Slab"],
    attempts: 1,
    result: "topped",
    thoughts: "Super flowy",
    date: DateTime.now(),
  ),
  ClimbAttempt(
    grade: "V1",
    styleTags: ['Volume', 'Overhang', 'Technical'],
    attempts: 4,
    result: "topped",
    thoughts: "Foot slipped at the top",
    date: DateTime.now().subtract(Duration(days: 0)),
  ),
ClimbAttempt(
    grade: "V1",
    styleTags: ['Dynamic', 'Crimpy', 'Slab'],
    attempts: 4,
    result: "topped",
    thoughts: "Crux was tricky",
    date: DateTime.now().subtract(Duration(days: 6)),
  ),
ClimbAttempt(
    grade: "V1",
    styleTags: ['Dynamic'],
    attempts: 1,
    result: "topped",
    thoughts: "Should rest more",
    date: DateTime.now().subtract(Duration(days: 7)),
  ),
ClimbAttempt(
    grade: "V1",
    styleTags: ['Crimpy'],
    attempts: 4,
    result: "topped",
    thoughts: "Really proud of this one",
    date: DateTime.now().subtract(Duration(days: 5)),
  ),
ClimbAttempt(
    grade: "V1",
    styleTags: ['Volume', 'Powerful'],
    attempts: 2,
    result: "topped",
    thoughts: "Tired but sent it",
    date: DateTime.now().subtract(Duration(days: 5)),
  ),
  ClimbAttempt(
    grade: "V1",
    styleTags: ['Slab'],
    attempts: 2,
    result: "topped",
    thoughts: "Super flowy",
    date: DateTime.now().subtract(Duration(days: 9)),
  ),
ClimbAttempt(
    grade: "V1",
    styleTags: ['Overhang'],
    attempts: 5,
    result: "topped",
    thoughts: "Missed a hold mid-way",
    date: DateTime.now().subtract(Duration(days: 8)),
  ),
ClimbAttempt(
    grade: "V1",
    styleTags: ['Volume', 'Dynamic'],
    attempts: 1,
    result: "topped",
    thoughts: "Needed better footwork",
    date: DateTime.now().subtract(Duration(days: 2)),
  ),
ClimbAttempt(
    grade: "V1",
    styleTags: ['Technical'],
    attempts: 4,
    result: "topped",
    thoughts: "Took way too many attempts",
    date: DateTime.now().subtract(Duration(days: 0)),
  ),
ClimbAttempt(
    grade: "V1",
    styleTags: ['Slab', 'Crimpy'],
    attempts: 1,
    result: "topped",
    thoughts: "Really proud of this one",
    date: DateTime.now().subtract(Duration(days: 4)),
  ),
ClimbAttempt(
    grade: "V1",
    styleTags: ['Powerful'],
    attempts: 4,
    result: "topped",
    thoughts: "Super flowy",
    date: DateTime.now().subtract(Duration(days: 7)),
  ),
ClimbAttempt(
    grade: "V1",
    styleTags: ['Dynamic'],
    attempts: 2,
    result: "topped",
    thoughts: "Missed a hold mid-way",
    date: DateTime.now().subtract(Duration(days: 4)),
  ),
ClimbAttempt(
    grade: "V1",
    styleTags: ['Volume'],
    attempts: 1,
    result: "topped",
    thoughts: "Crux was tricky",
    date: DateTime.now().subtract(Duration(days: 6)),
  ),
ClimbAttempt(
    grade: "V1",
    styleTags: ['Dynamic', 'Slab'],
    attempts: 4,
    result: "topped",
    thoughts: "Super flowy",
    date: DateTime.now().subtract(Duration(days: 10)),
  ),
ClimbAttempt(
    grade: "V1",
    styleTags: ['Dynamic'],
    attempts: 2,
    result: "topped",
    thoughts: "Foot slipped at the top",
    date: DateTime.now().subtract(Duration(days: 0)),
  ),
ClimbAttempt(
    grade: "V1",
    styleTags: ['Dynamic'],
    attempts: 1,
    result: "topped",
    thoughts: "Tired but sent it",
    date: DateTime.now().subtract(Duration(days: 5)),
  ),
ClimbAttempt(
    grade: "V1",
    styleTags: ['Slab'],
    attempts: 1,
    result: "topped",
    thoughts: "Really proud of this one",
    date: DateTime.now().subtract(Duration(days: 6)),
  ),
ClimbAttempt(
    grade: "V1",
    styleTags: ['Overhang', 'Slab'],
    attempts: 5,
    result: "topped",
    thoughts: "Super flowy",
    date: DateTime.now().subtract(Duration(days: 8)),
  ),
ClimbAttempt(
    grade: "V1",
    styleTags: ['Crimpy', 'Powerful'],
    attempts: 2,
    result: "topped",
    thoughts: "Missed a hold mid-way",
    date: DateTime.now().subtract(Duration(days: 10)),
  ),
ClimbAttempt(
    grade: "V1",
    styleTags: ['Powerful', 'Technical'],
    attempts: 2,
    result: "topped",
    thoughts: "Missed a hold mid-way",
    date: DateTime.now().subtract(Duration(days: 4)),
  ),
ClimbAttempt(
    grade: "V2",
    styleTags: ['Dynamic', 'Slab'],
    attempts: 6,
    result: "topped",
    thoughts: "Took way too many attempts",
    date: DateTime.now().subtract(Duration(days: 10)),
  ),
ClimbAttempt(
    grade: "V2",
    styleTags: ['Crimpy'],
    attempts: 6,
    result: "topped",
    thoughts: "Should rest more",
    date: DateTime.now().subtract(Duration(days: 3)),
  ),
ClimbAttempt(
    grade: "V2",
    styleTags: ['Overhang'],
    attempts: 3,
    result: "topped",
    thoughts: "Tired but sent it",
    date: DateTime.now().subtract(Duration(days: 10)),
  ),
ClimbAttempt(
    grade: "V2",
    styleTags: ['Technical', 'Powerful'],
    attempts: 6,
    result: "topped",
    thoughts: "Missed a hold mid-way",
    date: DateTime.now().subtract(Duration(days: 0)),
  ),
ClimbAttempt(
    grade: "V2",
    styleTags: ['Dynamic'],
    attempts: 6,
    result: "topped",
    thoughts: "Foot slipped at the top",
    date: DateTime.now().subtract(Duration(days: 8)),
  ),
ClimbAttempt(
    grade: "V2",
    styleTags: ['Powerful'],
    attempts: 9,
    result: "topped",
    thoughts: "Really proud of this one",
    date: DateTime.now().subtract(Duration(days: 9)),
  ),
ClimbAttempt(
    grade: "V2",
    styleTags: ['Technical'],
    attempts: 7,
    result: "topped",
    thoughts: "Tired but sent it",
    date: DateTime.now().subtract(Duration(days: 10)),
  ),
ClimbAttempt(
    grade: "V2",
    styleTags: ['Dynamic'],
    attempts: 9,
    result: "topped",
    thoughts: "Foot slipped at the top",
    date: DateTime.now().subtract(Duration(days: 6)),
  ),
ClimbAttempt(
    grade: "V2",
    styleTags: ['Volume'],
    attempts: 8,
    result: "topped",
    thoughts: "Crux was tricky",
    date: DateTime.now().subtract(Duration(days: 5)),
  ),
ClimbAttempt(
    grade: "V2",
    styleTags: ['Technical'],
    attempts: 1,
    result: "topped",
    thoughts: "Tired but sent it",
    date: DateTime.now().subtract(Duration(days: 6)),
  ),
ClimbAttempt(
    grade: "V3",
    styleTags: ['Powerful', 'Volume'],
    attempts: 2,
    result: "topped",
    thoughts: "Super flowy",
    date: DateTime.now().subtract(Duration(days: 1)),
  ),
ClimbAttempt(
    grade: "V3",
    styleTags: ['Slab'],
    attempts: 5,
    result: "topped",
    thoughts: "Tired but sent it",
    date: DateTime.now().subtract(Duration(days: 9)),
  ),
ClimbAttempt(
    grade: "V3",
    styleTags: ['Powerful', 'Crimpy'],
    attempts: 8,
    result: "topped",
    thoughts: "Foot slipped at the top",
    date: DateTime.now().subtract(Duration(days: 3)),
  ),
ClimbAttempt(
    grade: "V3",
    styleTags: ['Technical'],
    attempts: 5,
    result: "topped",
    thoughts: "Super flowy",
    date: DateTime.now().subtract(Duration(days: 8)),
  ),
ClimbAttempt(
    grade: "V3",
    styleTags: ['Technical'],
    attempts: 8,
    result: "topped",
    thoughts: "Beta worked perfectly",
    date: DateTime.now().subtract(Duration(days: 5)),
  ),
ClimbAttempt(
    grade: "V3",
    styleTags: ['Technical'],
    attempts: 3,
    result: "topped",
    thoughts: "Crux was tricky",
    date: DateTime.now().subtract(Duration(days: 5)),
  ),
ClimbAttempt(
    grade: "V4",
    styleTags: ['Slab'],
    attempts: 6,
    result: "topped",
    thoughts: "Really proud of this one",
    date: DateTime.now().subtract(Duration(days: 1)),
  ),
ClimbAttempt(
    grade: "V4",
    styleTags: ['Crimpy'],
    attempts: 11,
    result: "topped",
    thoughts: "Crux was tricky",
    date: DateTime.now().subtract(Duration(days: 9)),
  ),
ClimbAttempt(
    grade: "V4",
    styleTags: ['Dynamic', 'Slab'],
    attempts: 12,
    result: "topped",
    thoughts: "Took way too many attempts",
    date: DateTime.now().subtract(Duration(days: 0)),
  ),
ClimbAttempt(
    grade: "V4",
    styleTags: ['Crimpy'],
    attempts: 4,
    result: "topped",
    thoughts: "Tired but sent it",
    date: DateTime.now().subtract(Duration(days: 7)),
  ),
ClimbAttempt(
    grade: "V5",
    styleTags: ['Dynamic'],
    attempts: 4,
    result: "topped",
    thoughts: "Took way too many attempts",
    date: DateTime.now().subtract(Duration(days: 9)),
  ),
ClimbAttempt(
    grade: "V5",
    styleTags: ['Volume'],
    attempts: 14,
    result: "topped",
    thoughts: "Beta worked perfectly",
    date: DateTime.now().subtract(Duration(days: 1)),
  ),
ClimbAttempt(
    grade: "V5",
    styleTags: ['Technical'],
    attempts: 15,
    result: "topped",
    thoughts: "Missed a hold mid-way",
    date: DateTime.now().subtract(Duration(days: 4)),
  ),
ClimbAttempt(
    grade: "V5",
    styleTags: ['Technical'],
    attempts: 2,
    result: "topped",
    thoughts: "Missed a hold mid-way",
    date: DateTime.now().subtract(Duration(days: 9)),
  ),
ClimbAttempt(
    grade: "V5",
    styleTags: ['Dynamic'],
    attempts: 4,
    result: "topped",
    thoughts: "Should rest more",
    date: DateTime.now().subtract(Duration(days: 7)),
  ),
ClimbAttempt(
    grade: "V6",
    styleTags: ['Volume'],
    attempts: 6,
    result: "fell",
    thoughts: "Beta worked perfectly",
    date: DateTime.now().subtract(Duration(days: 10)),
  ),
ClimbAttempt(
    grade: "V6",
    styleTags: ['Crimpy'],
    attempts: 9,
    result: "fell",
    thoughts: "Crux was tricky",
    date: DateTime.now().subtract(Duration(days: 6)),
  ),
ClimbAttempt(
    grade: "V6",
    styleTags: ['Volume'],
    attempts: 13,
    result: "fell",
    thoughts: "Should rest more",
    date: DateTime.now().subtract(Duration(days: 0)),
  ),
ClimbAttempt(
    grade: "V6",
    styleTags: ['Powerful'],
    attempts: 8,
    result: "fell",
    thoughts: "Really proud of this one",
    date: DateTime.now().subtract(Duration(days: 8)),
  ),
ClimbAttempt(
    grade: "V7",
    styleTags: ['Volume'],
    attempts: 14,
    result: "fell",
    thoughts: "Crux was tricky",
    date: DateTime.now().subtract(Duration(days: 4)),
  ),
];
