import '../models/quest.dart';

final List<Quest> mockQuests = [
  Quest(
    id: "q1",
    name: "Climb 3 Overhang routes",
    type: "style",
    styleTag: "Overhang",
    grade: null,
    target: 3,
    progress: 1,
    completed: false,
  ),
  Quest(
    id: "q2",
    name: "Top a V5",
    type: "grade",
    styleTag: null,
    grade: "V5",
    target: 1,
    progress: 0,
    completed: false,
  ),
  Quest(
    id: "q3",
    name: "Log 10 climbs this week",
    type: "count",
    styleTag: null,
    grade: null,
    target: 10,
    progress: 6,
    completed: false,
  ),
  Quest(
    id: "q4",
    name: "Climb 2 Slab problems",
    type: "style",
    styleTag: "Slab",
    grade: null,
    target: 2,
    progress: 2,
    completed: true,
  ),
  Quest(
    id: "q5",
    name: "Top 5 climbs V3 or harder",
    type: "grade",
    styleTag: null,
    grade: "V3",
    target: 5,
    progress: 3,
    completed: false,
  ),
];
